contactform:
  description: This is a demo contact form and does not work. You can configure it
    to work on your side.
  emailconfig: abc
facts:
  experience: 5
  projects: 25
  customers: 100
keywords: portfolio, website, netlify, jekyll
author:
  resumelink: https://google.com
  name: John Doe
  cvlink: https://google.com
  phone: +1 123 456 7890
  first: John
  address: Gujarat, IN
  last: Doe
  dob: 01 Jan 2000
  passion: Web Developer, Graphic Designer
  languages: English, Gujarati, Hindi
  image: https://cdn.now.howstuffworks.com/media-content/0b7f4e9b-f59c-4024-9f06-b3dc12850ab7-1920-1080.jpg
  nationality: INDIAN
  email: support@getlocalhost.dev
  description: I am a Web Developer from India. I am very passionate and dedicated
    to my work. I have 5 years more work experience. I enjoy working in a team
    or individual.
social:
  facebook: ikaushalpatel
  github: mrkaushal
  instagram: mr.kaushal.p
  linkedin: mrkaushalp
  twitter: mr_kaushal_p
  website: "spece.netlify.app"
collections:
  portfolio:
    output: true
title: Spese Portfolio Theme
description: My Site
baseurl: ""
